server:
  port: 8081

spring:
  application:
    name: LCKonnect-Ingestor

crawling:
  lck:
    target_url:
      - "https://gol.gg/tournament/tournament-matchlist/LCK%202025%20Rounds%201-2/"
      - "https://gol.gg/tournament/tournament-matchlist/Worlds%20Main%20Event%202024/"
