server:
  port: 8081

spring:
  profiles:
    active: v1
  application:
    name: LCKonnect-Ingestor
  datasource:
    url: jdbc:mariadb://localhost:3306/lck
    username: lck
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

crawling:
  lck:
    target_match_url:
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%202021/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%20Playoffs%202021/
      - https://gol.gg/tournament/tournament-matchlist/MSI%202021/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%202021/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%20Playoffs%202021/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Regional%20Finals%202021/
      - https://gol.gg/tournament/tournament-matchlist/World%20Championship%202021/
      - https://gol.gg/tournament/tournament-matchlist/World%20Championship%20Play-In%202021/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%202022/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%20Playoffs%202022/
      - https://gol.gg/tournament/tournament-matchlist/MSI%202022/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%202022/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%20Playoffs%202022/
      - https://gol.gg/tournament/tournament-matchlist/World%20Championship%202022/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%202023/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%20Playoffs%202023/
      - https://gol.gg/tournament/tournament-matchlist/MSI%202023/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%202023/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%20Playoffs%202023/
      - https://gol.gg/tournament/tournament-matchlist/Worlds%20Main%20Event%202023/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%202024/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Spring%20Playoffs%202024/
      - https://gol.gg/tournament/tournament-matchlist/MSI%202024/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%202024/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Summer%20Playoffs%202024/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Regional%20Finals%202024/
      - https://gol.gg/tournament/tournament-matchlist/Worlds%20Main%20Event%202024/
      - https://gol.gg/tournament/tournament-matchlist/LCK%20Cup%202025/
      - https://gol.gg/tournament/tournament-matchlist/LCK%202025%20Road%20to%20MSI/
      - https://gol.gg/tournament/tournament-matchlist/2025%20Mid-Season%20Invitational/
      - https://gol.gg/tournament/tournament-matchlist/LCK%202025%20Rounds%201-2/
      - https://gol.gg/tournament/tournament-matchlist/LCK%202025%20Rounds%203-5/
      - https://gol.gg/tournament/tournament-matchlist/LCK%202025%20Season%20Play-In/
      - https://gol.gg/tournament/tournament-matchlist/LCK%202025%20Season%20Playoffs/

youtube:
  api:
    base_url: "https://www.googleapis.com"
    channel_id: "UCw1DsweY9b2AKGjV4kGJP1A"
    path:
      channel: "/youtube/v3/channels"
      playlist: "/youtube/v3/playlists"
      playlist_item_list: "/youtube/v3/playlistItems"

transform:
  map_data_path: ./data/lck_crawl_and_youtube_map2.json